"""
Cirq integration: custom exchange gate, silicon decoherence channels, the full
two-qubit Clifford group, and (interleaved) randomized benchmarking.

Two RB models are provided.

* ``CompiledCliffordRB`` — what an experiment runs. Every Clifford is compiled
  to native gates (±X/2, ±Y/2 EDSR pulses, virtual Z, CZ; 1.5 CZ per Clifford
  on average, see :mod:`clifford_compiler`), and noise is applied per physical
  gate: T1/T2* decoherence for the duration of every layer on both qubits,
  optional depolarising error per pulse / per CZ, and an optional non-ideal CZ
  unitary (e.g. a shaped pulse with residual leakage). The inverse is compiled
  the same way.
* ``run_randomized_benchmarking`` / ``run_interleaved_rb`` — a Clifford-level
  model: each Clifford is one ideal layer of fixed duration followed by
  decoherence. This is the right tool for interleaving an arbitrary synthesised
  unitary (e.g. a GRAPE √SWAP that is not a native gate), but it says nothing
  about compiled sequence length.

The two-qubit Clifford group C₂ (11 520 elements modulo phase) is generated by
breadth-first closure of {H⊗I, I⊗H, S⊗I, I⊗S, CNOT}.
"""

from __future__ import annotations

import warnings
from functools import lru_cache
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np
import scipy.optimize

from .noise import SiliconNoiseModel

try:
    import cirq

    HAS_CIRQ = True
except ImportError:  # pragma: no cover
    HAS_CIRQ = False
    cirq = None


# --------------------------------------------------------------------------- #
# Clifford groups
# --------------------------------------------------------------------------- #
_H = np.array([[1, 1], [1, -1]], dtype=np.complex128) / np.sqrt(2.0)
_S = np.array([[1, 0], [0, 1j]], dtype=np.complex128)
_I2 = np.eye(2, dtype=np.complex128)
_CNOT = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0]], dtype=np.complex128)


def clifford_key(u: np.ndarray, decimals: int = 5) -> bytes:
    """Phase-invariant hashable key of a unitary (first non-zero entry made real positive)."""
    flat = u.reshape(-1)
    idx = int(np.argmax(np.abs(flat) > 1e-9))
    phase = np.conj(flat[idx]) / abs(flat[idx])
    v = np.round(u * phase, decimals) + 0.0   # "+0.0" normalises signed zeros
    return np.concatenate([v.real.ravel(), v.imag.ravel()]).tobytes()


def _closure(generators: List[np.ndarray], dim: int) -> List[np.ndarray]:
    identity = np.eye(dim, dtype=np.complex128)
    seen = {clifford_key(identity): identity}
    queue = [identity]
    while queue:
        cur = queue.pop()
        for g in generators:
            nxt = g @ cur
            k = clifford_key(nxt)
            if k not in seen:
                seen[k] = nxt
                queue.append(nxt)
    return list(seen.values())


@lru_cache(maxsize=1)
def _cliffords_1q() -> Tuple[np.ndarray, ...]:
    return tuple(_closure([_H, _S], 2))


@lru_cache(maxsize=1)
def _cliffords_2q() -> Tuple[np.ndarray, ...]:
    gens = [np.kron(_H, _I2), np.kron(_I2, _H), np.kron(_S, _I2), np.kron(_I2, _S), _CNOT]
    return tuple(_closure(gens, 4))


def generate_single_qubit_cliffords() -> List[np.ndarray]:
    """The 24 single-qubit Cliffords (modulo global phase)."""
    return list(_cliffords_1q())


def generate_two_qubit_cliffords() -> List[np.ndarray]:
    """The 11 520 two-qubit Cliffords (modulo global phase); computed once and cached."""
    return list(_cliffords_2q())


# --------------------------------------------------------------------------- #
# Gate and simulator
# --------------------------------------------------------------------------- #
if HAS_CIRQ:

    class SiliconExchangeGate(cirq.Gate):
        """Two-qubit gate wrapping a synthesised exchange-pulse unitary."""

        def __init__(self, unitary: np.ndarray, name: str = "SiExchange"):
            super().__init__()
            unitary = np.asarray(unitary)
            if unitary.shape != (4, 4):
                raise ValueError(f"Expected 4x4 unitary matrix, got {unitary.shape}")
            self._unitary_matrix = np.array(unitary, dtype=np.complex128)
            self._name = name

        def _num_qubits_(self) -> int:
            return 2

        def _unitary_(self) -> np.ndarray:
            return self._unitary_matrix

        def _circuit_diagram_info_(self, args) -> "cirq.CircuitDiagramInfo":
            return cirq.CircuitDiagramInfo(wire_symbols=(f"[{self._name}]", f"[{self._name}]"))

        def __repr__(self) -> str:
            return f"SiliconExchangeGate(name='{self._name}')"

else:  # pragma: no cover

    class SiliconExchangeGate:  # type: ignore[no-redef]
        def __init__(self, *args, **kwargs):
            raise RuntimeError("Cirq is not installed.")


class CirqSiliconSimulator:
    """
    Appends T1 / T2* channels after every moment: generalized amplitude damping
    towards the thermal state (|1⟩ = |↓⟩ is the ground state, as in the Lindblad
    model) and phase damping.
    """

    def __init__(self, noise_model: Optional[SiliconNoiseModel] = None):
        self.noise = noise_model or SiliconNoiseModel()

    def damping_parameters(self, gate_duration_ns: float) -> Tuple[float, float]:
        """(γ_amp, γ_phase) for one moment of duration ``gate_duration_ns``."""
        rates = self.noise.lindblad_rates_per_ns()
        t = float(gate_duration_ns)
        gamma_amp = 1.0 - np.exp(-rates["gamma_1"] * t)
        # phase_damp(γ) multiplies coherences by sqrt(1-γ): exp(-γφ t) ⇒ γ = 1 - exp(-2 γφ t)
        gamma_phase = 1.0 - np.exp(-2.0 * rates["gamma_phi"] * t)
        return float(gamma_amp), float(gamma_phase)

    def create_noisy_circuit(self, circuit: "cirq.Circuit", gate_duration_ns: float = 40.0) -> "cirq.Circuit":
        if not HAS_CIRQ:
            raise RuntimeError("Cirq is not installed.")
        g_amp, g_phi = self.damping_parameters(gate_duration_ns)
        p_up = self.noise.excited_state_population()
        noisy = cirq.Circuit()
        for moment in circuit:
            noisy.append(moment)
            for q in moment.qubits:
                if g_amp > 0:
                    noisy.append(cirq.generalized_amplitude_damp(p_up, g_amp).on(q))
                if g_phi > 0:
                    noisy.append(cirq.phase_damp(g_phi).on(q))
        return noisy


# --------------------------------------------------------------------------- #
# Randomized benchmarking
# --------------------------------------------------------------------------- #
def rb_fit(lengths: Sequence[int], survival: Sequence[float]) -> Tuple[float, float, float]:
    """Fit F(m) = A·pᵐ + B; returns (A, p, B)."""
    m = np.asarray(lengths, dtype=float)
    y = np.asarray(survival, dtype=float)

    def model(mm, A, p, B):
        return A * p**mm + B

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        try:
            popt, _ = scipy.optimize.curve_fit(
                model, m, y, p0=[0.75, 0.98, 0.25],
                bounds=([0.0, 0.0, 0.0], [1.0, 1.0, 1.0]), maxfev=20000,
            )
        except Exception:
            return 0.75, float("nan"), 0.25
    return float(popt[0]), float(popt[1]), float(popt[2])


def clifford_error_from_p(p: float, d: int = 4) -> float:
    """Average error per Clifford r = (1 − p)(1 − 1/d)."""
    return float((1.0 - p) * (1.0 - 1.0 / d))


def _clifford_pool(clifford_set: str) -> List[np.ndarray]:
    if clifford_set == "two_qubit":
        return generate_two_qubit_cliffords()
    if clifford_set == "local":
        c1 = generate_single_qubit_cliffords()
        return [np.kron(a, b) for a in c1 for b in c1]
    raise ValueError("clifford_set must be 'two_qubit' or 'local'")


def _rb_survival(
    lengths: Sequence[int],
    n_sequences: int,
    noise_model: Optional[SiliconNoiseModel],
    rng: np.random.Generator,
    pool: List[np.ndarray],
    interleave: Optional[np.ndarray] = None,
    interleaved_depolarizing: float = 0.0,
    gate_duration_ns: float = 40.0,
) -> Tuple[List[float], List[float]]:
    q0, q1 = cirq.LineQubit.range(2)
    sim = CirqSiliconSimulator(noise_model)
    dm_sim = cirq.DensityMatrixSimulator()
    means, stds = [], []
    for length in lengths:
        fids = []
        for _ in range(n_sequences):
            circuit = cirq.Circuit()
            acc = np.eye(4, dtype=np.complex128)
            for _ in range(int(length)):
                c = pool[rng.integers(len(pool))]
                circuit.append(cirq.MatrixGate(c).on(q0, q1))
                acc = c @ acc
                if interleave is not None:
                    circuit.append(SiliconExchangeGate(interleave).on(q0, q1))
                    if interleaved_depolarizing > 0:
                        circuit.append(cirq.depolarize(interleaved_depolarizing, n_qubits=2).on(q0, q1))
                    acc = interleave @ acc
            circuit.append(cirq.MatrixGate(acc.conj().T).on(q0, q1))
            noisy = sim.create_noisy_circuit(circuit, gate_duration_ns)
            rho = dm_sim.simulate(noisy).final_density_matrix
            fids.append(float(np.real(rho[0, 0])))
        means.append(float(np.mean(fids)))
        stds.append(float(np.std(fids)))
    return means, stds


def run_randomized_benchmarking(
    lengths: Sequence[int],
    n_sequences_per_length: int = 15,
    n_shots: int = 0,  # kept for API compatibility; density-matrix simulation is exact
    noise_model: Optional[SiliconNoiseModel] = None,
    seed: Optional[int] = None,
    clifford_set: str = "two_qubit",
    gate_duration_ns: float = 40.0,
) -> Dict[str, Any]:
    """
    Two-qubit Clifford RB: survival probability of |00⟩ versus sequence length,
    fitted to A·pᵐ + B. ``clifford_error`` is the average error per Clifford.
    """
    if not HAS_CIRQ:
        raise RuntimeError("Cirq is not installed.")
    rng = np.random.default_rng(seed)
    pool = _clifford_pool(clifford_set)
    means, stds = _rb_survival(lengths, n_sequences_per_length, noise_model, rng, pool,
                               gate_duration_ns=gate_duration_ns)
    A, p, B = rb_fit(lengths, means)
    return {
        "lengths": list(lengths),
        "fidelities": means,
        "std_errors": stds,
        "decay_p": p,
        "fit_A": A,
        "fit_B": B,
        "clifford_error": clifford_error_from_p(p),
        "clifford_set": clifford_set,
    }


def run_interleaved_rb(
    target_gate: np.ndarray,
    lengths: Sequence[int],
    n_sequences_per_length: int = 15,
    noise_model: Optional[SiliconNoiseModel] = None,
    seed: Optional[int] = None,
    clifford_set: str = "two_qubit",
    interleaved_depolarizing: float = 0.0,
    gate_duration_ns: float = 40.0,
) -> Dict[str, Any]:
    """
    Interleaved RB isolating the error of ``target_gate``:
        r_gate = (1 − 1/d)(1 − p_int / p_ref).
    ``interleaved_depolarizing`` adds a two-qubit depolarising channel after
    every interleaved gate (useful to validate the estimator).
    """
    if not HAS_CIRQ:
        raise RuntimeError("Cirq is not installed.")
    rng = np.random.default_rng(seed)
    pool = _clifford_pool(clifford_set)
    ref_means, ref_stds = _rb_survival(lengths, n_sequences_per_length, noise_model, rng, pool,
                                       gate_duration_ns=gate_duration_ns)
    int_means, int_stds = _rb_survival(lengths, n_sequences_per_length, noise_model, rng, pool,
                                       interleave=np.asarray(target_gate, dtype=np.complex128),
                                       interleaved_depolarizing=interleaved_depolarizing,
                                       gate_duration_ns=gate_duration_ns)
    _, p_ref, _ = rb_fit(lengths, ref_means)
    _, p_int, _ = rb_fit(lengths, int_means)
    ratio = p_int / p_ref if p_ref > 0 else 0.0
    gate_error = max(0.0, (1.0 - 1.0 / 4.0) * (1.0 - ratio))
    return {
        "lengths": list(lengths),
        "ref_fidelities": ref_means,
        "ref_std_errors": ref_stds,
        "interleaved_fidelities": int_means,
        "interleaved_std_errors": int_stds,
        "decay_p_ref": p_ref,
        "decay_p_interleaved": p_int,
        "gate_error": gate_error,
        "gate_fidelity": 1.0 - gate_error,
        "clifford_set": clifford_set,
    }


# --------------------------------------------------------------------------- #
# Native-gate (compiled) randomized benchmarking
# --------------------------------------------------------------------------- #
def _unitary_superop(U: np.ndarray) -> np.ndarray:
    return np.kron(U.conj(), U)


def _depolarizing_superop(p: float, n_qubits: int) -> np.ndarray:
    """ρ ↦ (1 − p)ρ + p/(4ⁿ−1) Σ_{P≠I} PρP  (cirq.depolarize convention)."""
    from functools import reduce
    paulis1 = [np.eye(2), np.array([[0, 1], [1, 0]]), np.array([[0, -1j], [1j, 0]]), np.diag([1.0, -1.0])]
    import itertools
    d = 2**n_qubits
    S = (1.0 - p) * np.eye(d * d, dtype=np.complex128)
    for combo in itertools.product(range(4), repeat=n_qubits):
        if all(c == 0 for c in combo):
            continue
        P = reduce(np.kron, [paulis1[c] for c in combo]).astype(np.complex128)
        S = S + (p / (4**n_qubits - 1)) * _unitary_superop(P)
    return S


def best_z_corrected_cz(U: np.ndarray) -> np.ndarray:
    """Apply the virtual-Z corrections that make a controlled-phase-like U closest to CZ."""
    d = np.diag(U)
    a = np.angle(d[0])
    z = np.diag([1.0, np.exp(-1j * (np.angle(d[1]) - a)), np.exp(-1j * (np.angle(d[2]) - a)),
                 np.exp(-1j * (np.angle(d[1]) + np.angle(d[2]) - 2 * a))]) * np.exp(-1j * a)
    return z @ np.asarray(U, dtype=np.complex128)


class CompiledCliffordRB:
    """
    Two-qubit Clifford RB on native spin-qubit gates.

    Parameters
    ----------
    noise_model : T1 / T2* (and temperature) of both electrons
    t_pulse_ns : duration of one ±π/2 EDSR pulse (layers run both qubits in parallel)
    t_cz_ns : duration of the CZ
    p_pulse : extra single-qubit depolarising probability per π/2 pulse
    p_cz : extra two-qubit depolarising probability per CZ
    cz_unitary : the implemented CZ (default ideal); pass e.g. a shaped-pulse
        propagator after ``best_z_corrected_cz`` to include coherent leakage.
    """

    def __init__(
        self,
        noise_model: Optional[SiliconNoiseModel] = None,
        t_pulse_ns: float = 50.0,
        t_cz_ns: float = 100.0,
        p_pulse: float = 0.0,
        p_cz: float = 0.0,
        cz_unitary: Optional[np.ndarray] = None,
    ):
        from .clifford_compiler import one_qubit_cliffords, two_qubit_cliffords

        self.noise = noise_model or SiliconNoiseModel(t1_us=1e9, t2_star_us=1e9, charge_noise_amp=0.0, overhauser_sigma=0.0)
        self.t_pulse, self.t_cz = float(t_pulse_ns), float(t_cz_ns)
        self.p_pulse, self.p_cz = float(p_pulse), float(p_cz)
        self.c1 = one_qubit_cliffords()
        self.c2 = two_qubit_cliffords()
        cz = np.diag([1, 1, 1, -1]).astype(np.complex128) if cz_unitary is None else np.asarray(cz_unitary, dtype=np.complex128)
        self._idle_cache: Dict[int, np.ndarray] = {}
        dep_cz = _depolarizing_superop(self.p_cz, 2) if self.p_cz > 0 else np.eye(16)
        self.cz_superop = self._idle(self.t_cz) @ dep_cz @ _unitary_superop(cz)
        self._local_cache: Dict[Tuple[int, int], np.ndarray] = {}
        self._clifford_cache: Dict[int, np.ndarray] = {}
        dep1 = _depolarizing_superop(self.p_pulse, 1) if self.p_pulse > 0 else np.eye(4)
        self._dep_pulse = [np.linalg.matrix_power(dep1, k) for k in range(4)]

    # ----------------------------------------------------------------- #
    def _idle(self, duration_ns: float) -> np.ndarray:
        key = int(round(duration_ns * 1000))
        if key not in self._idle_cache:
            self._idle_cache[key] = self.noise.idle_superoperator(duration_ns)
        return self._idle_cache[key]

    def _local_superop(self, a: int, b: int) -> np.ndarray:
        if (a, b) not in self._local_cache:
            ca, cb = self.c1[a], self.c1[b]
            U = np.kron(ca.unitary, cb.unitary)
            # per-qubit pulse errors: (D_a ⊗ D_b) in column-stacking order is a reshuffle; build via Kraus-free product
            dep = _two_local(self._dep_pulse[ca.n_pulses], self._dep_pulse[cb.n_pulses])
            duration = max(ca.n_pulses, cb.n_pulses) * self.t_pulse
            self._local_cache[(a, b)] = self._idle(duration) @ dep @ _unitary_superop(U)
        return self._local_cache[(a, b)]

    def clifford_superop(self, index: int) -> np.ndarray:
        if index not in self._clifford_cache:
            S = np.eye(16, dtype=np.complex128)
            for kind, arg in self.c2[index].native_sequence():
                S = (self.cz_superop if kind == "cz" else self._local_superop(*arg)) @ S
            self._clifford_cache[index] = S
        return self._clifford_cache[index]

    def circuit(self, index: int, qubits: Optional[Sequence["cirq.Qid"]] = None) -> "cirq.Circuit":
        """The compiled native-gate circuit of Clifford ``index`` (for inspection / export)."""
        if not HAS_CIRQ:
            raise RuntimeError("Cirq is not installed.")
        q = list(qubits) if qubits is not None else cirq.LineQubit.range(2)
        gate = {"X/2": cirq.rx(np.pi / 2), "-X/2": cirq.rx(-np.pi / 2), "Y/2": cirq.ry(np.pi / 2),
                "-Y/2": cirq.ry(-np.pi / 2), "S": cirq.S}
        c = cirq.Circuit()
        for kind, arg in self.c2[index].native_sequence():
            if kind == "cz":
                c.append(cirq.CZ(q[0], q[1]), strategy=cirq.InsertStrategy.NEW_THEN_INLINE)
            else:
                ops = [gate[g](q[0]) for g in self.c1[arg[0]].gates] + [gate[g](q[1]) for g in self.c1[arg[1]].gates]
                c.append(ops)
        return c

    # ----------------------------------------------------------------- #
    def _survival(self, lengths, n_sequences, rng, interleave_cz: bool) -> Tuple[List[float], List[float]]:
        from .clifford_compiler import lookup_two_qubit_clifford

        cz_ideal = np.diag([1, 1, 1, -1]).astype(np.complex128)
        rho0 = np.zeros(16, dtype=np.complex128); rho0[0] = 1.0     # vec(|00⟩⟨00|)
        means, stds = [], []
        for m in lengths:
            vals = []
            for _ in range(int(n_sequences)):
                vec = rho0.copy()
                acc = np.eye(4, dtype=np.complex128)
                for _ in range(int(m)):
                    k = int(rng.integers(len(self.c2)))
                    vec = self.clifford_superop(k) @ vec
                    acc = self.c2[k].unitary @ acc
                    if interleave_cz:
                        vec = self.cz_superop @ vec
                        acc = cz_ideal @ acc
                inv = lookup_two_qubit_clifford(acc.conj().T)
                vec = self.clifford_superop(inv) @ vec
                vals.append(float(np.real(vec[0])))
            means.append(float(np.mean(vals)))
            stds.append(float(np.std(vals)))
        return means, stds

    def run(self, lengths: Sequence[int], n_sequences: int = 20, seed: Optional[int] = None) -> Dict[str, Any]:
        """Reference RB: survival of |00⟩, fit, error per Clifford, native gate counts."""
        rng = np.random.default_rng(seed)
        means, stds = self._survival(lengths, n_sequences, rng, interleave_cz=False)
        A, p, B = rb_fit(lengths, means)
        return {"lengths": list(lengths), "fidelities": means, "std_errors": stds, "decay_p": p, "fit_A": A, "fit_B": B,
                "clifford_error": clifford_error_from_p(p), **self.gate_statistics()}

    def run_interleaved_cz(self, lengths: Sequence[int], n_sequences: int = 20, seed: Optional[int] = None) -> Dict[str, Any]:
        """Interleaved RB of the native CZ: r_CZ = (1 − 1/d)(1 − p_int/p_ref)."""
        rng = np.random.default_rng(seed)
        ref, _ = self._survival(lengths, n_sequences, rng, interleave_cz=False)
        inter, _ = self._survival(lengths, n_sequences, rng, interleave_cz=True)
        _, p_ref, _ = rb_fit(lengths, ref)
        _, p_int, _ = rb_fit(lengths, inter)
        err = max(0.0, 0.75 * (1.0 - p_int / p_ref)) if p_ref > 0 else float("nan")
        return {"lengths": list(lengths), "ref_fidelities": ref, "interleaved_fidelities": inter,
                "decay_p_ref": p_ref, "decay_p_interleaved": p_int, "cz_error": err}

    def gate_statistics(self) -> Dict[str, float]:
        n_cz = np.array([c.n_cz for c in self.c2])
        pulses = np.array([sum(max(self.c1[a].n_pulses, self.c1[b].n_pulses) for a, b in c.layers) for c in self.c2])
        durations = n_cz * self.t_cz + pulses * self.t_pulse
        return {"mean_cz_per_clifford": float(n_cz.mean()), "mean_pulse_layers_per_clifford": float(pulses.mean()),
                "mean_clifford_duration_ns": float(durations.mean())}


def _two_local(S_a: np.ndarray, S_b: np.ndarray) -> np.ndarray:
    """Column-stacking superoperator of E_a ⊗ E_b from single-qubit superoperators."""
    # vec(ρ) index for ρ[(i1 i2), (j1 j2)] in column stacking is (j1 j2) * 4 + (i1 i2).
    # E_a ⊗ E_b acts as S[(j1' i1'), (j1 i1)] ⊗ S[(j2' i2'), (j2 i2)]; reorder indices accordingly.
    T = np.einsum("abcd,efgh->aebfcgdh", S_a.reshape(2, 2, 2, 2), S_b.reshape(2, 2, 2, 2))
    return T.reshape(16, 16)
