"""
Cirq integration: custom exchange gate, silicon decoherence channels, the full
two-qubit Clifford group, and (interleaved) randomized benchmarking.

The two-qubit Clifford group C₂ (11 520 elements modulo phase) is generated by
breadth-first closure of {H⊗I, I⊗H, S⊗I, I⊗S, CNOT}; RB sequences draw
uniformly from it, so the reported decay is a genuine two-qubit Clifford RB.
"""

from __future__ import annotations

import warnings
from functools import lru_cache
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np
import scipy.optimize

from .noise import SiliconNoiseModel

try:
    import cirq

    HAS_CIRQ = True
except ImportError:  # pragma: no cover
    HAS_CIRQ = False
    cirq = None


# --------------------------------------------------------------------------- #
# Clifford groups
# --------------------------------------------------------------------------- #
_H = np.array([[1, 1], [1, -1]], dtype=np.complex128) / np.sqrt(2.0)
_S = np.array([[1, 0], [0, 1j]], dtype=np.complex128)
_I2 = np.eye(2, dtype=np.complex128)
_CNOT = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0]], dtype=np.complex128)


def clifford_key(u: np.ndarray, decimals: int = 5) -> bytes:
    """Phase-invariant hashable key of a unitary (first non-zero entry made real positive)."""
    flat = u.reshape(-1)
    idx = int(np.argmax(np.abs(flat) > 1e-9))
    phase = np.conj(flat[idx]) / abs(flat[idx])
    v = np.round(u * phase, decimals) + 0.0   # "+0.0" normalises signed zeros
    return np.concatenate([v.real.ravel(), v.imag.ravel()]).tobytes()


def _closure(generators: List[np.ndarray], dim: int) -> List[np.ndarray]:
    identity = np.eye(dim, dtype=np.complex128)
    seen = {clifford_key(identity): identity}
    queue = [identity]
    while queue:
        cur = queue.pop()
        for g in generators:
            nxt = g @ cur
            k = clifford_key(nxt)
            if k not in seen:
                seen[k] = nxt
                queue.append(nxt)
    return list(seen.values())


@lru_cache(maxsize=1)
def _cliffords_1q() -> Tuple[np.ndarray, ...]:
    return tuple(_closure([_H, _S], 2))


@lru_cache(maxsize=1)
def _cliffords_2q() -> Tuple[np.ndarray, ...]:
    gens = [np.kron(_H, _I2), np.kron(_I2, _H), np.kron(_S, _I2), np.kron(_I2, _S), _CNOT]
    return tuple(_closure(gens, 4))


def generate_single_qubit_cliffords() -> List[np.ndarray]:
    """The 24 single-qubit Cliffords (modulo global phase)."""
    return list(_cliffords_1q())


def generate_two_qubit_cliffords() -> List[np.ndarray]:
    """The 11 520 two-qubit Cliffords (modulo global phase); computed once and cached."""
    return list(_cliffords_2q())


# --------------------------------------------------------------------------- #
# Gate and simulator
# --------------------------------------------------------------------------- #
if HAS_CIRQ:

    class SiliconExchangeGate(cirq.Gate):
        """Two-qubit gate wrapping a synthesised exchange-pulse unitary."""

        def __init__(self, unitary: np.ndarray, name: str = "SiExchange"):
            super().__init__()
            unitary = np.asarray(unitary)
            if unitary.shape != (4, 4):
                raise ValueError(f"Expected 4x4 unitary matrix, got {unitary.shape}")
            self._unitary_matrix = np.array(unitary, dtype=np.complex128)
            self._name = name

        def _num_qubits_(self) -> int:
            return 2

        def _unitary_(self) -> np.ndarray:
            return self._unitary_matrix

        def _circuit_diagram_info_(self, args) -> "cirq.CircuitDiagramInfo":
            return cirq.CircuitDiagramInfo(wire_symbols=(f"[{self._name}]", f"[{self._name}]"))

        def __repr__(self) -> str:
            return f"SiliconExchangeGate(name='{self._name}')"

else:  # pragma: no cover

    class SiliconExchangeGate:  # type: ignore[no-redef]
        def __init__(self, *args, **kwargs):
            raise RuntimeError("Cirq is not installed.")


class CirqSiliconSimulator:
    """Appends T1 / T2* channels (amplitude & phase damping) after every moment."""

    def __init__(self, noise_model: Optional[SiliconNoiseModel] = None):
        self.noise = noise_model or SiliconNoiseModel()

    def damping_parameters(self, gate_duration_ns: float) -> Tuple[float, float]:
        """(γ_amp, γ_phase) for one moment of duration ``gate_duration_ns``."""
        rates = self.noise.lindblad_rates_per_ns()
        t = float(gate_duration_ns)
        gamma_amp = 1.0 - np.exp(-rates["gamma_1"] * t)
        # phase_damp(γ) multiplies coherences by sqrt(1-γ): exp(-γφ t) ⇒ γ = 1 - exp(-2 γφ t)
        gamma_phase = 1.0 - np.exp(-2.0 * rates["gamma_phi"] * t)
        return float(gamma_amp), float(gamma_phase)

    def create_noisy_circuit(self, circuit: "cirq.Circuit", gate_duration_ns: float = 40.0) -> "cirq.Circuit":
        if not HAS_CIRQ:
            raise RuntimeError("Cirq is not installed.")
        g_amp, g_phi = self.damping_parameters(gate_duration_ns)
        noisy = cirq.Circuit()
        for moment in circuit:
            noisy.append(moment)
            for q in moment.qubits:
                if g_amp > 0:
                    noisy.append(cirq.amplitude_damp(g_amp).on(q))
                if g_phi > 0:
                    noisy.append(cirq.phase_damp(g_phi).on(q))
        return noisy


# --------------------------------------------------------------------------- #
# Randomized benchmarking
# --------------------------------------------------------------------------- #
def rb_fit(lengths: Sequence[int], survival: Sequence[float]) -> Tuple[float, float, float]:
    """Fit F(m) = A·pᵐ + B; returns (A, p, B)."""
    m = np.asarray(lengths, dtype=float)
    y = np.asarray(survival, dtype=float)

    def model(mm, A, p, B):
        return A * p**mm + B

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        try:
            popt, _ = scipy.optimize.curve_fit(
                model, m, y, p0=[0.75, 0.98, 0.25],
                bounds=([0.0, 0.0, 0.0], [1.0, 1.0, 1.0]), maxfev=20000,
            )
        except Exception:
            return 0.75, float("nan"), 0.25
    return float(popt[0]), float(popt[1]), float(popt[2])


def clifford_error_from_p(p: float, d: int = 4) -> float:
    """Average error per Clifford r = (1 − p)(1 − 1/d)."""
    return float((1.0 - p) * (1.0 - 1.0 / d))


def _clifford_pool(clifford_set: str) -> List[np.ndarray]:
    if clifford_set == "two_qubit":
        return generate_two_qubit_cliffords()
    if clifford_set == "local":
        c1 = generate_single_qubit_cliffords()
        return [np.kron(a, b) for a in c1 for b in c1]
    raise ValueError("clifford_set must be 'two_qubit' or 'local'")


def _rb_survival(
    lengths: Sequence[int],
    n_sequences: int,
    noise_model: Optional[SiliconNoiseModel],
    rng: np.random.Generator,
    pool: List[np.ndarray],
    interleave: Optional[np.ndarray] = None,
    interleaved_depolarizing: float = 0.0,
    gate_duration_ns: float = 40.0,
) -> Tuple[List[float], List[float]]:
    q0, q1 = cirq.LineQubit.range(2)
    sim = CirqSiliconSimulator(noise_model)
    dm_sim = cirq.DensityMatrixSimulator()
    means, stds = [], []
    for length in lengths:
        fids = []
        for _ in range(n_sequences):
            circuit = cirq.Circuit()
            acc = np.eye(4, dtype=np.complex128)
            for _ in range(int(length)):
                c = pool[rng.integers(len(pool))]
                circuit.append(cirq.MatrixGate(c).on(q0, q1))
                acc = c @ acc
                if interleave is not None:
                    circuit.append(SiliconExchangeGate(interleave).on(q0, q1))
                    if interleaved_depolarizing > 0:
                        circuit.append(cirq.depolarize(interleaved_depolarizing, n_qubits=2).on(q0, q1))
                    acc = interleave @ acc
            circuit.append(cirq.MatrixGate(acc.conj().T).on(q0, q1))
            noisy = sim.create_noisy_circuit(circuit, gate_duration_ns)
            rho = dm_sim.simulate(noisy).final_density_matrix
            fids.append(float(np.real(rho[0, 0])))
        means.append(float(np.mean(fids)))
        stds.append(float(np.std(fids)))
    return means, stds


def run_randomized_benchmarking(
    lengths: Sequence[int],
    n_sequences_per_length: int = 15,
    n_shots: int = 0,  # kept for API compatibility; density-matrix simulation is exact
    noise_model: Optional[SiliconNoiseModel] = None,
    seed: Optional[int] = None,
    clifford_set: str = "two_qubit",
    gate_duration_ns: float = 40.0,
) -> Dict[str, Any]:
    """
    Two-qubit Clifford RB: survival probability of |00⟩ versus sequence length,
    fitted to A·pᵐ + B. ``clifford_error`` is the average error per Clifford.
    """
    if not HAS_CIRQ:
        raise RuntimeError("Cirq is not installed.")
    rng = np.random.default_rng(seed)
    pool = _clifford_pool(clifford_set)
    means, stds = _rb_survival(lengths, n_sequences_per_length, noise_model, rng, pool,
                               gate_duration_ns=gate_duration_ns)
    A, p, B = rb_fit(lengths, means)
    return {
        "lengths": list(lengths),
        "fidelities": means,
        "std_errors": stds,
        "decay_p": p,
        "fit_A": A,
        "fit_B": B,
        "clifford_error": clifford_error_from_p(p),
        "clifford_set": clifford_set,
    }


def run_interleaved_rb(
    target_gate: np.ndarray,
    lengths: Sequence[int],
    n_sequences_per_length: int = 15,
    noise_model: Optional[SiliconNoiseModel] = None,
    seed: Optional[int] = None,
    clifford_set: str = "two_qubit",
    interleaved_depolarizing: float = 0.0,
    gate_duration_ns: float = 40.0,
) -> Dict[str, Any]:
    """
    Interleaved RB isolating the error of ``target_gate``:
        r_gate = (1 − 1/d)(1 − p_int / p_ref).
    ``interleaved_depolarizing`` adds a two-qubit depolarising channel after
    every interleaved gate (useful to validate the estimator).
    """
    if not HAS_CIRQ:
        raise RuntimeError("Cirq is not installed.")
    rng = np.random.default_rng(seed)
    pool = _clifford_pool(clifford_set)
    ref_means, ref_stds = _rb_survival(lengths, n_sequences_per_length, noise_model, rng, pool,
                                       gate_duration_ns=gate_duration_ns)
    int_means, int_stds = _rb_survival(lengths, n_sequences_per_length, noise_model, rng, pool,
                                       interleave=np.asarray(target_gate, dtype=np.complex128),
                                       interleaved_depolarizing=interleaved_depolarizing,
                                       gate_duration_ns=gate_duration_ns)
    _, p_ref, _ = rb_fit(lengths, ref_means)
    _, p_int, _ = rb_fit(lengths, int_means)
    ratio = p_int / p_ref if p_ref > 0 else 0.0
    gate_error = max(0.0, (1.0 - 1.0 / 4.0) * (1.0 - ratio))
    return {
        "lengths": list(lengths),
        "ref_fidelities": ref_means,
        "ref_std_errors": ref_stds,
        "interleaved_fidelities": int_means,
        "interleaved_std_errors": int_stds,
        "decay_p_ref": p_ref,
        "decay_p_interleaved": p_int,
        "gate_error": gate_error,
        "gate_fidelity": 1.0 - gate_error,
        "clifford_set": clifford_set,
    }
